name: NPM release ðŸš€

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  build:
    name: Build package ðŸ“¦
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Update npm
        run: npm install -g npm@latest
      - name: Install npm deps
        run: npm i
      - name: Build package ðŸ—
        run: |
          mkdir pkg
          npm pack --pack-destination pkg
      - uses: actions/upload-artifact@v5
        name: Upload build artifacts ðŸ“¦
        with:
          name: pkg
          retention-days: 7
          path: ./pkg

  # create-github-release:
  #   name: Create GitHub release ðŸ™
  #   # Upload wheel to a GitHub release. It remains available as a build artifact for a while as well.
  #   needs: build
  #   runs-on: ubuntu-24.04
  #   permissions:
  #     contents: write
  #   steps:
  #     - name: Download build artifacts ðŸ“¦
  #       uses: actions/download-artifact@v6
  #       with:
  #         path: ./pkg
  #     - name: Create draft release ðŸ™
  #       run: >-
  #         gh release create
  #         --verify-tag
  #         --draft
  #         --repo ${{ github.repository }}
  #         --title ${{ github.ref_name }}
  #         ${{ github.ref_name }}
  #         pkg/*
  #       env:
  #         GH_TOKEN: ${{ github.token }}

  publish-npm:
    name: Publish ðŸš€
    needs: build
    # Wait for approval before attempting to upload to NPM. This allows reviewing the
    # files in the draft release.
    environment: publish
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Update npm
        run: npm install -g npm@latest
      - name: Download build artifacts ðŸ“¦
        uses: actions/download-artifact@v6
        with:
          path: ./pkg
      - name: Publish to NPM ðŸš€
        run: npm publish ./pkg/*.tgz --tag latest --access public --provenance
      # - name: Publish GitHub release ðŸ™
      #   run: >-
      #     gh release edit
      #     --draft=false
      #     --repo ${{ github.repository }}
      #     ${{ github.ref_name }}
      #   env:
      #     GH_TOKEN: ${{ github.token }}
